// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxhitamrnzjeacputqxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4aGl0YW1ybnpqZWFjcHV0cXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTY3MzMsImV4cCI6MjA3MTQ3MjczM30.CkLqCS5bsSO7DkG7Ip5TeCUQbmFhgCVPhObdKKa22rM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});